apiVersion: rabbitmq.com/v1beta2
kind: RabbitmqCluster
metadata:
  name: federation
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins:
    - rabbitmq_federation
    - rabbitmq_federation_management
  tls:
    secretName: tls-secret
